### ISSUE TITLE
expose felix configuration settings in values.yaml?

### ISSUE THREAD

**Issue by jkroepke** [flexkube/calico-helm-chart#2]
Hi,

I installed calico using this cart first time on my test lab on AWS. On AWS, the src/dest check needs to be disabled for instances. But settings can't be set on autoscale groups.

For this scenario, calico can disable the source/destination check on the instance.

I guess I could set this by define `FELIX_AWSSRCDSTCHECK=Disable` on the calico-node, but there is no chance to define this inside the chart.

See: https://docs.projectcalico.org/reference/resources/felixconfig#aws-iam-rolepolicy-for-source-destination-check-configuration

**Comment by invidian** [comment]
It should be fine to add an ability to specify extra environment variables for Felix DaemonSet via values.yaml. I guess that would be sufficient. @jkroepke would you like to create a PR implementing it?

**Comment by jkroepke** [comment]
Yes.

What about existing values (expect `valueFrom`)? Should I move them to values, too? Then users could override them.

https://github.com/flexkube/calico-helm-chart/blob/038c4ebb7940f7854005dba47b6ccfda49cbd693/templates/calico.yaml#L585-L665

**Comment by invidian** [comment]
Most of the values which are there comes from upstream Calico, I think it should be fine to keep them. I would prefer to stay as close to the upstream as possible, to make manifest updates easier.

 If one wants to modify them, we add extra env vars at the bottom, so they will override the previous ones, like in the example below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - name: foo
    image: nginx
    env:
    - name: FOO
      value: foo
    - name: FOO
      value: bar
```
